name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-macos: 4000000000

      - name: CI
        run: nix develop --command make ci
